<?php

$paises = [
    ['codigo' =>'AD', 'pais' => 'Andorra'],
    ['codigo' =>'AE', 'pais' => 'Emiratos &Aacute;rabes Unidos'],
    ['codigo' =>'AF', 'pais' => 'Afganist&aacute;n'],
    ['codigo' =>'AG', 'pais' => 'Antigua y Barbuda'],
    ['codigo' =>'AI', 'pais' => 'Anguila'],
    ['codigo' =>'AL', 'pais' => 'Albania'],
    ['codigo' =>'AM', 'pais' => 'Armenia'],
    ['codigo' =>'AN', 'pais' => 'Antillas Neerlandesas'],
    ['codigo' =>'AO', 'pais' => 'Angola'],
    ['codigo' =>'AQ', 'pais' => 'Ant&aacute;rtida'],
    ['codigo' =>'AR', 'pais' => 'Argentina'],
    ['codigo' =>'AS', 'pais' => 'Samoa Americana'],
    ['codigo' =>'AT', 'pais' => 'Austria'],
    ['codigo' =>'AU', 'pais' => 'Australia'],
    ['codigo' =>'AW', 'pais' => 'Aruba'],
    ['codigo' =>'AX', 'pais' => 'Islas &Aacute;land'],
    ['codigo' =>'AZ', 'pais' => 'Azerbaiy&aacute;n'],
    ['codigo' =>'BA', 'pais' => 'Bosnia y Herzegovina'],
    ['codigo' =>'BB', 'pais' => 'Barbados'],
    ['codigo' =>'BD', 'pais' => 'Bangladesh'],
    ['codigo' =>'BE', 'pais' => 'B&eacute;lgica'],
    ['codigo' =>'BF', 'pais' => 'Burkina Faso'],
    ['codigo' =>'BG', 'pais' => 'Bulgaria'],
    ['codigo' =>'BH', 'pais' => 'Bahr&eacute;in'],
    ['codigo' =>'BI', 'pais' => 'Burundi'],
    ['codigo' =>'BJ', 'pais' => 'Benin'],
    ['codigo' =>'BL', 'pais' => 'San Bartolom&eacute;'],
    ['codigo' =>'BM', 'pais' => 'Bermudas'],
    ['codigo' =>'BN', 'pais' => 'Brun&eacute;i'],
    ['codigo' =>'BO', 'pais' => 'Bolivia'],
    ['codigo' =>'BR', 'pais' => 'Brasil'],
    ['codigo' =>'BS', 'pais' => 'Bahamas'],
    ['codigo' =>'BT', 'pais' => 'Bhut&aacute;n'],
    ['codigo' =>'BV', 'pais' => 'Isla Bouvet'],
    ['codigo' =>'BW', 'pais' => 'Botsuana'],
    ['codigo' =>'BY', 'pais' => 'Belar&uacute;s'],
    ['codigo' =>'BZ', 'pais' => 'Belice'],
    ['codigo' =>'CA', 'pais' => 'Canad&aacute;'],
    ['codigo' =>'CC', 'pais' => 'Islas Cocos'],
    ['codigo' =>'CF', 'pais' => 'Rep&uacute;blica Centro-Africana'],
    ['codigo' =>'CG', 'pais' => 'Congo'],
    ['codigo' =>'CH', 'pais' => 'Suiza'],
    ['codigo' =>'CI', 'pais' => 'Costa de Marfil'],
    ['codigo' =>'CK', 'pais' => 'Islas Cook'],
    ['codigo' =>'CL', 'pais' => 'Chile'],
    ['codigo' =>'CM', 'pais' => 'Camer&uacute;n'],
    ['codigo' =>'CN', 'pais' => 'China'],
    ['codigo' =>'CO', 'pais' => 'Colombia'],
    ['codigo' =>'CR', 'pais' => 'Costa Rica'],
    ['codigo' =>'CU', 'pais' => 'Cuba'],
    ['codigo' =>'CV', 'pais' => 'Cabo Verde'],
    ['codigo' =>'CX', 'pais' => 'Islas Christmas'],
    ['codigo' =>'CY', 'pais' => 'Chipre'],
    ['codigo' =>'CZ', 'pais' => 'Rep&uacute;blica Checa'],
    ['codigo' =>'DE', 'pais' => 'Alemania'],
    ['codigo' =>'DJ', 'pais' => 'Yibuti'],
    ['codigo' =>'DK', 'pais' => 'Dinamarca'],
    ['codigo' =>'DM', 'pais' => 'Dom&iacute;nica'],
    ['codigo' =>'DO', 'pais' => 'Rep&uacute;blica Dominicana'],
    ['codigo' =>'DZ', 'pais' => 'Argel'],
    ['codigo' =>'EC', 'pais' => 'Ecuador'],
    ['codigo' =>'EE', 'pais' => 'Estonia'],
    ['codigo' =>'EG', 'pais' => 'Egipto'],
    ['codigo' =>'EH', 'pais' => 'Sahara Occidental'],
    ['codigo' =>'ER', 'pais' => 'Eritrea'],
    ['codigo' =>'ES', 'pais' => 'Espa&ntilde;a'],
    ['codigo' =>'ET', 'pais' => 'Etiop&iacute;a'],
    ['codigo' =>'FI', 'pais' => 'Finlandia'],
    ['codigo' =>'FJ', 'pais' => 'Fiji'],
    ['codigo' =>'FK', 'pais' => 'Islas Malvinas'],
    ['codigo' =>'FM', 'pais' => 'Micronesia'],
    ['codigo' =>'FO', 'pais' => 'Islas Faroe'],
    ['codigo' =>'FR', 'pais' => 'Francia'],
    ['codigo' =>'GA', 'pais' => 'Gab&oacute;n'],
    ['codigo' =>'GB', 'pais' => 'Reino Unido'],
    ['codigo' =>'GD', 'pais' => 'Granada'],
    ['codigo' =>'GE', 'pais' => 'Georgia'],
    ['codigo' =>'GF', 'pais' => 'Guayana Francesa'],
    ['codigo' =>'GG', 'pais' => 'Guernsey'],
    ['codigo' =>'GH', 'pais' => 'Ghana'],
    ['codigo' =>'GI', 'pais' => 'Gibraltar'],
    ['codigo' =>'GL', 'pais' => 'Groenlandia'],
    ['codigo' =>'GM', 'pais' => 'Gambia'],
    ['codigo' =>'GN', 'pais' => 'Guinea'],
    ['codigo' =>'GP', 'pais' => 'Guadalupe'],
    ['codigo' =>'GQ', 'pais' => 'Guinea Ecuatorial'],
    ['codigo' =>'GR', 'pais' => 'Grecia'],
    ['codigo' =>'GS', 'pais' => 'Georgia del Sur e Islas Sandwich del Sur'],
    ['codigo' =>'GT', 'pais' => 'Guatemala'],
    ['codigo' =>'GU', 'pais' => 'Guam'],
    ['codigo' =>'GW', 'pais' => 'Guinea-Bissau'],
    ['codigo' =>'GY', 'pais' => 'Guayana'],
    ['codigo' =>'HK', 'pais' => 'Hong Kong'],
    ['codigo' =>'HM', 'pais' => 'Islas Heard y McDonald'],
    ['codigo' =>'HN', 'pais' => 'Honduras'],
    ['codigo' =>'HR', 'pais' => 'Croacia'],
    ['codigo' =>'HT', 'pais' => 'Hait&iacute;'],
    ['codigo' =>'HU', 'pais' => 'Hungr&iacute;a'],
    ['codigo' =>'ID', 'pais' => 'Indonesia'],
    ['codigo' =>'IE', 'pais' => 'Irlanda'],
    ['codigo' =>'IL', 'pais' => 'Israel'],
    ['codigo' =>'IM', 'pais' => 'Isla de Man'],
    ['codigo' =>'IN', 'pais' => 'India'],
    ['codigo' =>'IO', 'pais' => 'Territorio Brit&aacute;nico del Oc&eacute;ano &Iacute;ndico'],
    ['codigo' =>'IQ', 'pais' => 'Irak'],
    ['codigo' =>'IR', 'pais' => 'Ir&aacute;n'],
    ['codigo' =>'IS', 'pais' => 'Islandia'],
    ['codigo' =>'IT', 'pais' => 'Italia'],
    ['codigo' =>'JE', 'pais' => 'Jersey'],
    ['codigo' =>'JM', 'pais' => 'Jamaica'],
    ['codigo' =>'JO', 'pais' => 'Jordania'],
    ['codigo' =>'JP', 'pais' => 'Jap&oacute;n'],
    ['codigo' =>'KE', 'pais' => 'Kenia'],
    ['codigo' =>'KG', 'pais' => 'Kirguist&aacute;n'],
    ['codigo' =>'KH', 'pais' => 'Camboya'],
    ['codigo' =>'KI', 'pais' => 'Kiribati'],
    ['codigo' =>'KM', 'pais' => 'Comoros'],
    ['codigo' =>'KN', 'pais' => 'San Crist&oacute;bal y Nieves'],
    ['codigo' =>'KP', 'pais' => 'Corea del Norte'],
    ['codigo' =>'KR', 'pais' => 'Corea del Sur'],
    ['codigo' =>'KW', 'pais' => 'Kuwait'],
    ['codigo' =>'KY', 'pais' => 'Islas Caim&aacute;n'],
    ['codigo' =>'KZ', 'pais' => 'Kazajst&aacute;n'],
    ['codigo' =>'LA', 'pais' => 'Laos'],
    ['codigo' =>'LB', 'pais' => 'L&iacute;bano'],
    ['codigo' =>'LC', 'pais' => 'Santa Luc&iacute;a'],
    ['codigo' =>'LI', 'pais' => 'Liechtenstein'],
    ['codigo' =>'LK', 'pais' => 'Sri Lanka'],
    ['codigo' =>'LR', 'pais' => 'Liberia'],
    ['codigo' =>'LS', 'pais' => 'Lesotho'],
    ['codigo' =>'LT', 'pais' => 'Lituania'],
    ['codigo' =>'LU', 'pais' => 'Luxemburgo'],
    ['codigo' =>'LV', 'pais' => 'Letonia'],
    ['codigo' =>'LY', 'pais' => 'Libia'],
    ['codigo' =>'MA', 'pais' => 'Marruecos'],
    ['codigo' =>'MC', 'pais' => 'M&oacute;naco'],
    ['codigo' =>'MD', 'pais' => 'Moldova'],
    ['codigo' =>'ME', 'pais' => 'Montenegro'],
    ['codigo' =>'MG', 'pais' => 'Madagascar'],
    ['codigo' =>'MH', 'pais' => 'Islas Marshall'],
    ['codigo' =>'MK', 'pais' => 'Macedonia'],
    ['codigo' =>'ML', 'pais' => 'Mali'],
    ['codigo' =>'MM', 'pais' => 'Myanmar'],
    ['codigo' =>'MN', 'pais' => 'Mongolia'],
    ['codigo' =>'MO', 'pais' => 'Macao'],
    ['codigo' =>'MQ', 'pais' => 'Martinica'],
    ['codigo' =>'MR', 'pais' => 'Mauritania'],
    ['codigo' =>'MS', 'pais' => 'Montserrat'],
    ['codigo' =>'MT', 'pais' => 'Malta'],
    ['codigo' =>'MU', 'pais' => 'Mauricio'],
    ['codigo' =>'MV', 'pais' => 'Maldivas'],
    ['codigo' =>'MW', 'pais' => 'Malawi'],
    ['codigo' =>'MX', 'pais' => 'M&eacute;xico'],
    ['codigo' =>'MY', 'pais' => 'Malasia'],
    ['codigo' =>'MZ', 'pais' => 'Mozambique'],
    ['codigo' =>'NA', 'pais' => 'Namibia'],
    ['codigo' =>'NC', 'pais' => 'Nueva Caledonia'],
    ['codigo' =>'NE', 'pais' => 'N&iacute;ger'],
    ['codigo' =>'NF', 'pais' => 'Islas Norkfolk'],
    ['codigo' =>'NG', 'pais' => 'Nigeria'],
    ['codigo' =>'NI', 'pais' => 'Nicaragua'],
    ['codigo' =>'NL', 'pais' => 'Pa&iacute;ses Bajos'],
    ['codigo' =>'NO', 'pais' => 'Noruega'],
    ['codigo' =>'NP', 'pais' => 'Nepal'],
    ['codigo' =>'NR', 'pais' => 'Nauru'],
    ['codigo' =>'NU', 'pais' => 'Niue'],
    ['codigo' =>'NZ', 'pais' => 'Nueva Zelanda'],
    ['codigo' =>'OM', 'pais' => 'Om&aacute;n'],
    ['codigo' =>'PA', 'pais' => 'Panam&aacute;'],
    ['codigo' =>'PE', 'pais' => 'Per&uacute;'],
    ['codigo' =>'PF', 'pais' => 'Polinesia Francesa'],
    ['codigo' =>'PG', 'pais' => 'Pap&uacute;a Nueva Guinea'],
    ['codigo' =>'PH', 'pais' => 'Filipinas'],
    ['codigo' =>'PK', 'pais' => 'Pakist&aacute;n'],
    ['codigo' =>'PL', 'pais' => 'Polonia'],
    ['codigo' =>'PM', 'pais' => 'San Pedro y Miquel&oacute;n'],
    ['codigo' =>'PN', 'pais' => 'Islas Pitcairn'],
    ['codigo' =>'PR', 'pais' => 'Puerto Rico'],
    ['codigo' =>'PS', 'pais' => 'Palestina'],
    ['codigo' =>'PT', 'pais' => 'Portugal'],
    ['codigo' =>'PW', 'pais' => 'Islas Palaos'],
    ['codigo' =>'PY', 'pais' => 'Paraguay'],
    ['codigo' =>'QA', 'pais' => 'Qatar'],
    ['codigo' =>'RE', 'pais' => 'Reuni&oacute;n'],
    ['codigo' =>'RO', 'pais' => 'Ruman&iacute;a'],
    ['codigo' =>'RS', 'pais' => 'Serbia y Montenegro'],
    ['codigo' =>'RU', 'pais' => 'Rusia'],
    ['codigo' =>'RW', 'pais' => 'Ruanda'],
    ['codigo' =>'SA', 'pais' => 'Arabia Saudita'],
    ['codigo' =>'SB', 'pais' => 'Islas Solom&oacute;n'],
    ['codigo' =>'SC', 'pais' => 'Seychelles'],
    ['codigo' =>'SD', 'pais' => 'Sud&aacute;n'],
    ['codigo' =>'SE', 'pais' => 'Suecia'],
    ['codigo' =>'SG', 'pais' => 'Singapur'],
    ['codigo' =>'SH', 'pais' => 'Santa Elena'],
    ['codigo' =>'SI', 'pais' => 'Eslovenia'],
    ['codigo' =>'SJ', 'pais' => 'Islas Svalbard y Jan Mayen'],
    ['codigo' =>'SK', 'pais' => 'Eslovaquia'],
    ['codigo' =>'SL', 'pais' => 'Sierra Leona'],
    ['codigo' =>'SM', 'pais' => 'San Marino'],
    ['codigo' =>'SN', 'pais' => 'Senegal'],
    ['codigo' =>'SO', 'pais' => 'Somalia'],
    ['codigo' =>'SR', 'pais' => 'Surinam'],
    ['codigo' =>'ST', 'pais' => 'Santo Tom&eacute; y Pr&iacute;ncipe'],
    ['codigo' =>'SV', 'pais' => 'El Salvador'],
    ['codigo' =>'SY', 'pais' => 'Siria'],
    ['codigo' =>'SZ', 'pais' => 'Suazilandia'],
    ['codigo' =>'TC', 'pais' => 'Islas Turcas y Caicos'],
    ['codigo' =>'TD', 'pais' => 'Chad'],
    ['codigo' =>'TF', 'pais' => 'Territorios Australes Franceses'],
    ['codigo' =>'TG', 'pais' => 'Togo'],
    ['codigo' =>'TH', 'pais' => 'Tailandia'],
    ['codigo' =>'TH', 'pais' => 'Tanzania'],
    ['codigo' =>'TJ', 'pais' => 'Tayikist&aacute;n'],
    ['codigo' =>'TK', 'pais' => 'Tokelau'],
    ['codigo' =>'TL', 'pais' => 'Timor-Leste'],
    ['codigo' =>'TM', 'pais' => 'Turkmenist&aacute;n'],
    ['codigo' =>'TN', 'pais' => 'T&uacute;nez'],
    ['codigo' =>'TO', 'pais' => 'Tonga'],
    ['codigo' =>'TR', 'pais' => 'Turqu&iacute;a'],
    ['codigo' =>'TT', 'pais' => 'Trinidad y Tobago'],
    ['codigo' =>'TV', 'pais' => 'Tuvalu'],
    ['codigo' =>'TW', 'pais' => 'Taiw&aacute;n'],
    ['codigo' =>'UA', 'pais' => 'Ucrania'],
    ['codigo' =>'UG', 'pais' => 'Uganda'],
    ['codigo' =>'US', 'pais' => 'Estados Unidos de Am&eacute;rica'],
    ['codigo' =>'UY', 'pais' => 'Uruguay'],
    ['codigo' =>'UZ', 'pais' => 'Uzbekist&aacute;n'],
    ['codigo' =>'VA', 'pais' => 'Ciudad del Vaticano'],
    ['codigo' =>'VC', 'pais' => 'San Vicente y las Granadinas'],
    ['codigo' =>'VE', 'pais' => 'Venezuela'],
    ['codigo' =>'VG', 'pais' => 'Islas V&iacute;rgenes Brit&aacute;nicas'],
    ['codigo' =>'VI', 'pais' => 'Islas V&iacute;rgenes de los Estados Unidos de Am&eacute;rica'],
    ['codigo' =>'VN', 'pais' => 'Vietnam'],
    ['codigo' =>'VU', 'pais' => 'Vanuatu'],
    ['codigo' =>'WF', 'pais' => 'Wallis y Futuna'],
    ['codigo' =>'WS', 'pais' => 'Samoa'],
    ['codigo' =>'YE', 'pais' => 'Yemen'],
    ['codigo' =>'YT', 'pais' => 'Mayotte'],
    ['codigo' =>'ZA', 'pais' => 'Sud&aacute;frica']
];