<?php
$paises = [
    ['codigo' =>'AND', 'pais' => 'Andorra'],
    ['codigo' =>'ARE', 'pais' => 'Emiratos &Aacute;rabes Unidos'],
    ['codigo' =>'AFG', 'pais' => 'Afganist&aacute;n'],
    ['codigo' =>'ATG', 'pais' => 'Antigua y Barbuda'],
    ['codigo' =>'AIA', 'pais' => 'Anguila'],
    ['codigo' =>'ALB', 'pais' => 'Albania'],
    ['codigo' =>'ARM', 'pais' => 'Armenia'],
    ['codigo' =>'ANT', 'pais' => 'Antillas Neerlandesas'],
    ['codigo' =>'AGO', 'pais' => 'Angola'],
    ['codigo' =>'ATA', 'pais' => 'Ant&aacute;rtida'],
    ['codigo' =>'ARG', 'pais' => 'Argentina'],
    ['codigo' =>'ASM', 'pais' => 'Samoa Americana'],
    ['codigo' =>'AUT', 'pais' => 'Austria'],
    ['codigo' =>'AUS', 'pais' => 'Australia'],
    ['codigo' =>'ABW', 'pais' => 'Aruba'],
    ['codigo' =>'ALA', 'pais' => 'Islas &Aacute;land'],
    ['codigo' =>'AZE', 'pais' => 'Azerbaiy&aacute;n'],
    ['codigo' =>'BIH', 'pais' => 'Bosnia y Herzegovina'],
    ['codigo' =>'BRB', 'pais' => 'Barbados'],
    ['codigo' =>'BGD', 'pais' => 'Bangladesh'],
    ['codigo' =>'BEL', 'pais' => 'B&eacute;lgica'],
    ['codigo' =>'BFA', 'pais' => 'Burkina Faso'],
    ['codigo' =>'BGR', 'pais' => 'Bulgaria'],
    ['codigo' =>'BHR', 'pais' => 'Bahr&eacute;in'],
    ['codigo' =>'BDI', 'pais' => 'Burundi'],
    ['codigo' =>'BEN', 'pais' => 'Benin'],
    ['codigo' =>'BLM', 'pais' => 'San Bartolom&eacute;'],
    ['codigo' =>'BMU', 'pais' => 'Bermudas'],
    ['codigo' =>'BRN', 'pais' => 'Brun&eacute;i'],
    ['codigo' =>'BOL', 'pais' => 'Bolivia'],
    ['codigo' =>'BRA', 'pais' => 'Brasil'],
    ['codigo' =>'BHS', 'pais' => 'Bahamas'],
    ['codigo' =>'BTN', 'pais' => 'Bhut&aacute;n'],
    ['codigo' =>'BVT', 'pais' => 'Isla Bouvet'],
    ['codigo' =>'BWA', 'pais' => 'Botsuana'],
    ['codigo' =>'BLR', 'pais' => 'Belar&uacute;s'],
    ['codigo' =>'BLZ', 'pais' => 'Belice'],
    ['codigo' =>'CAN', 'pais' => 'Canad&aacute;'],
    ['codigo' =>'CCK', 'pais' => 'Islas Cocos'],
    ['codigo' =>'CAF', 'pais' => 'Rep&uacute;blica Centro-Africana'],
    ['codigo' =>'COG', 'pais' => 'Congo'],
    ['codigo' =>'CHE', 'pais' => 'Suiza'],
    ['codigo' =>'CIV', 'pais' => 'Costa de Marfil'],
    ['codigo' =>'COK', 'pais' => 'Islas Cook'],
    ['codigo' =>'CHL', 'pais' => 'Chile'],
    ['codigo' =>'CMR', 'pais' => 'Camer&uacute;n'],
    ['codigo' =>'CHN', 'pais' => 'China'],
    ['codigo' =>'COL', 'pais' => 'Colombia'],
    ['codigo' =>'CRI', 'pais' => 'Costa Rica'],
    ['codigo' =>'CUB', 'pais' => 'Cuba'],
    ['codigo' =>'CPV', 'pais' => 'Cabo Verde'],
    ['codigo' =>'CXR', 'pais' => 'Islas Christmas'],
    ['codigo' =>'CYP', 'pais' => 'Chipre'],
    ['codigo' =>'CZE', 'pais' => 'Rep&uacute;blica Checa'],
    ['codigo' =>'DEU', 'pais' => 'Alemania'],
    ['codigo' =>'DJI', 'pais' => 'Yibuti'],
    ['codigo' =>'DNK', 'pais' => 'Dinamarca'],
    ['codigo' =>'DMA', 'pais' => 'Dom&iacute;nica'],
    ['codigo' =>'DOM', 'pais' => 'Rep&uacute;blica Dominicana'],
    ['codigo' =>'DZA', 'pais' => 'Argel'],
    ['codigo' =>'ECU', 'pais' => 'Ecuador'],
    ['codigo' =>'EST', 'pais' => 'Estonia'],
    ['codigo' =>'EGY', 'pais' => 'Egipto'],
    ['codigo' =>'ESH', 'pais' => 'Sahara Occidental'],
    ['codigo' =>'ERI', 'pais' => 'Eritrea'],
    ['codigo' =>'ESP', 'pais' => 'Espa&ntilde;a'],
    ['codigo' =>'ETH', 'pais' => 'Etiop&iacute;a'],
    ['codigo' =>'FIN', 'pais' => 'Finlandia'],
    ['codigo' =>'FJI', 'pais' => 'Fiji'],
    ['codigo' =>'KLK', 'pais' => 'Islas Malvinas'],
    ['codigo' =>'FSM', 'pais' => 'Micronesia'],
    ['codigo' =>'FRO', 'pais' => 'Islas Faroe'],
    ['codigo' =>'FRA', 'pais' => 'Francia'],
    ['codigo' =>'GAB', 'pais' => 'Gab&oacute;n'],
    ['codigo' =>'GBR', 'pais' => 'Reino Unido'],
    ['codigo' =>'GRD', 'pais' => 'Granada'],
    ['codigo' =>'GEO', 'pais' => 'Georgia'],
    ['codigo' =>'GUF', 'pais' => 'Guayana Francesa'],
    ['codigo' =>'GGY', 'pais' => 'Guernsey'],
    ['codigo' =>'GHA', 'pais' => 'Ghana'],
    ['codigo' =>'GIB', 'pais' => 'Gibraltar'],
    ['codigo' =>'GRL', 'pais' => 'Groenlandia'],
    ['codigo' =>'GMB', 'pais' => 'Gambia'],
    ['codigo' =>'GIN', 'pais' => 'Guinea'],
    ['codigo' =>'GLP', 'pais' => 'Guadalupe'],
    ['codigo' =>'GNQ', 'pais' => 'Guinea Ecuatorial'],
    ['codigo' =>'GRC', 'pais' => 'Grecia'],
    ['codigo' =>'SGS', 'pais' => 'Georgia del Sur e Islas Sandwich del Sur'],
    ['codigo' =>'GTM', 'pais' => 'Guatemala'],
    ['codigo' =>'GUM', 'pais' => 'Guam'],
    ['codigo' =>'GNB', 'pais' => 'Guinea-Bissau'],
    ['codigo' =>'GUY', 'pais' => 'Guayana'],
    ['codigo' =>'HKG', 'pais' => 'Hong Kong'],
    ['codigo' =>'HMD', 'pais' => 'Islas Heard y McDonald'],
    ['codigo' =>'HND', 'pais' => 'Honduras'],
    ['codigo' =>'HRV', 'pais' => 'Croacia'],
    ['codigo' =>'HTI', 'pais' => 'Hait&iacute;'],
    ['codigo' =>'HUN', 'pais' => 'Hungr&iacute;a'],
    ['codigo' =>'IDN', 'pais' => 'Indonesia'],
    ['codigo' =>'IRL', 'pais' => 'Irlanda'],
    ['codigo' =>'ISR', 'pais' => 'Israel'],
    ['codigo' =>'IMN', 'pais' => 'Isla de Man'],
    ['codigo' =>'IND', 'pais' => 'India'],
    ['codigo' =>'IOT', 'pais' => 'Territorio Brit&aacute;nico del Oc&eacute;ano &Iacute;ndico'],
    ['codigo' =>'IRQ', 'pais' => 'Irak'],
    ['codigo' =>'IRN', 'pais' => 'Ir&aacute;n'],
    ['codigo' =>'ISL', 'pais' => 'Islandia'],
    ['codigo' =>'ITA', 'pais' => 'Italia'],
    ['codigo' =>'JEY', 'pais' => 'Jersey'],
    ['codigo' =>'JAM', 'pais' => 'Jamaica'],
    ['codigo' =>'JOR', 'pais' => 'Jordania'],
    ['codigo' =>'JPN', 'pais' => 'Jap&oacute;n'],
    ['codigo' =>'KEN', 'pais' => 'Kenia'],
    ['codigo' =>'KGZ', 'pais' => 'Kirguist&aacute;n'],
    ['codigo' =>'KHM', 'pais' => 'Camboya'],
    ['codigo' =>'KIR', 'pais' => 'Kiribati'],
    ['codigo' =>'COM', 'pais' => 'Comoros'],
    ['codigo' =>'KNA', 'pais' => 'San Crist&oacute;bal y Nieves'],
    ['codigo' =>'PRK', 'pais' => 'Corea del Norte'],
    ['codigo' =>'KOR', 'pais' => 'Corea del Sur'],
    ['codigo' =>'KWT', 'pais' => 'Kuwait'],
    ['codigo' =>'CYM', 'pais' => 'Islas Caim&aacute;n'],
    ['codigo' =>'KAZ', 'pais' => 'Kazajst&aacute;n'],
    ['codigo' =>'LAO', 'pais' => 'Laos'],
    ['codigo' =>'LBN', 'pais' => 'L&iacute;bano'],
    ['codigo' =>'LCA', 'pais' => 'Santa Luc&iacute;a'],
    ['codigo' =>'LIE', 'pais' => 'Liechtenstein'],
    ['codigo' =>'LKA', 'pais' => 'Sri Lanka'],
    ['codigo' =>'LBR', 'pais' => 'Liberia'],
    ['codigo' =>'LSO', 'pais' => 'Lesotho'],
    ['codigo' =>'LTU', 'pais' => 'Lituania'],
    ['codigo' =>'LUX', 'pais' => 'Luxemburgo'],
    ['codigo' =>'LVA', 'pais' => 'Letonia'],
    ['codigo' =>'LBY', 'pais' => 'Libia'],
    ['codigo' =>'MAR', 'pais' => 'Marruecos'],
    ['codigo' =>'MCO', 'pais' => 'M&oacute;naco'],
    ['codigo' =>'MDA', 'pais' => 'Moldova'],
    ['codigo' =>'MNE', 'pais' => 'Montenegro'],
    ['codigo' =>'MDG', 'pais' => 'Madagascar'],
    ['codigo' =>'MHL', 'pais' => 'Islas Marshall'],
    ['codigo' =>'MKD', 'pais' => 'Macedonia'],
    ['codigo' =>'MLI', 'pais' => 'Mali'],
    ['codigo' =>'MMR', 'pais' => 'Myanmar'],
    ['codigo' =>'MNG', 'pais' => 'Mongolia'],
    ['codigo' =>'MAC', 'pais' => 'Macao'],
    ['codigo' =>'MTQ', 'pais' => 'Martinica'],
    ['codigo' =>'MRT', 'pais' => 'Mauritania'],
    ['codigo' =>'MSR', 'pais' => 'Montserrat'],
    ['codigo' =>'MLT', 'pais' => 'Malta'],
    ['codigo' =>'MUS', 'pais' => 'Mauricio'],
    ['codigo' =>'MDV', 'pais' => 'Maldivas'],
    ['codigo' =>'MWI', 'pais' => 'Malawi'],
    ['codigo' =>'MEX', 'pais' => 'M&eacute;xico'],
    ['codigo' =>'MYS', 'pais' => 'Malasia'],
    ['codigo' =>'MOZ', 'pais' => 'Mozambique'],
    ['codigo' =>'NAM', 'pais' => 'Namibia'],
    ['codigo' =>'NCL', 'pais' => 'Nueva Caledonia'],
    ['codigo' =>'NER', 'pais' => 'N&iacute;ger'],
    ['codigo' =>'NFK', 'pais' => 'Islas Norkfolk'],
    ['codigo' =>'NGA', 'pais' => 'Nigeria'],
    ['codigo' =>'NIC', 'pais' => 'Nicaragua'],
    ['codigo' =>'NLD', 'pais' => 'Pa&iacute;ses Bajos'],
    ['codigo' =>'NOR', 'pais' => 'Noruega'],
    ['codigo' =>'NPL', 'pais' => 'Nepal'],
    ['codigo' =>'NRU', 'pais' => 'Nauru'],
    ['codigo' =>'NIU', 'pais' => 'Niue'],
    ['codigo' =>'NZL', 'pais' => 'Nueva Zelanda'],
    ['codigo' =>'OMN', 'pais' => 'Om&aacute;n'],
    ['codigo' =>'PAN', 'pais' => 'Panam&aacute;'],
    ['codigo' =>'PER', 'pais' => 'Per&uacute;'],
    ['codigo' =>'PYF', 'pais' => 'Polinesia Francesa'],
    ['codigo' =>'PNG', 'pais' => 'Pap&uacute;a Nueva Guinea'],
    ['codigo' =>'PHL', 'pais' => 'Filipinas'],
    ['codigo' =>'PAK', 'pais' => 'Pakist&aacute;n'],
    ['codigo' =>'POL', 'pais' => 'Polonia'],
    ['codigo' =>'SPM', 'pais' => 'San Pedro y Miquel&oacute;n'],
    ['codigo' =>'PCN', 'pais' => 'Islas Pitcairn'],
    ['codigo' =>'PRI', 'pais' => 'Puerto Rico'],
    ['codigo' =>'PSE', 'pais' => 'Palestina'],
    ['codigo' =>'PRT', 'pais' => 'Portugal'],
    ['codigo' =>'PLW', 'pais' => 'Islas Palaos'],
    ['codigo' =>'PRY', 'pais' => 'Paraguay'],
    ['codigo' =>'QAT', 'pais' => 'Qatar'],
    ['codigo' =>'REU', 'pais' => 'Reuni&oacute;n'],
    ['codigo' =>'ROU', 'pais' => 'Ruman&iacute;a'],
    ['codigo' =>'SRB', 'pais' => 'Serbia y Montenegro'],
    ['codigo' =>'RUS', 'pais' => 'Rusia'],
    ['codigo' =>'RWA', 'pais' => 'Ruanda'],
    ['codigo' =>'SAU', 'pais' => 'Arabia Saudita'],
    ['codigo' =>'SLB', 'pais' => 'Islas Solom&oacute;n'],
    ['codigo' =>'SYC', 'pais' => 'Seychelles'],
    ['codigo' =>'SDN', 'pais' => 'Sud&aacute;n'],
    ['codigo' =>'SWE', 'pais' => 'Suecia'],
    ['codigo' =>'SGP', 'pais' => 'Singapur'],
    ['codigo' =>'SHN', 'pais' => 'Santa Elena'],
    ['codigo' =>'SVN', 'pais' => 'Eslovenia'],
    ['codigo' =>'SJM', 'pais' => 'Islas Svalbard y Jan Mayen'],
    ['codigo' =>'SVK', 'pais' => 'Eslovaquia'],
    ['codigo' =>'SLE', 'pais' => 'Sierra Leona'],
    ['codigo' =>'SMR', 'pais' => 'San Marino'],
    ['codigo' =>'SEN', 'pais' => 'Senegal'],
    ['codigo' =>'SOM', 'pais' => 'Somalia'],
    ['codigo' =>'SUR', 'pais' => 'Surinam'],
    ['codigo' =>'STP', 'pais' => 'Santo Tom&eacute; y Pr&iacute;ncipe'],
    ['codigo' =>'SLV', 'pais' => 'El Salvador'],
    ['codigo' =>'SYR', 'pais' => 'Siria'],
    ['codigo' =>'SWZ', 'pais' => 'Suazilandia'],
    ['codigo' =>'TCA', 'pais' => 'Islas Turcas y Caicos'],
    ['codigo' =>'TCD', 'pais' => 'Chad'],
    ['codigo' =>'ATF', 'pais' => 'Territorios Australes Franceses'],
    ['codigo' =>'TGO', 'pais' => 'Togo'],
    ['codigo' =>'THA', 'pais' => 'Tailandia'],
    ['codigo' =>'TZA', 'pais' => 'Tanzania'],
    ['codigo' =>'TJK', 'pais' => 'Tayikist&aacute;n'],
    ['codigo' =>'TKL', 'pais' => 'Tokelau'],
    ['codigo' =>'TLS', 'pais' => 'Timor-Leste'],
    ['codigo' =>'TKM', 'pais' => 'Turkmenist&aacute;n'],
    ['codigo' =>'TUN', 'pais' => 'T&uacute;nez'],
    ['codigo' =>'TON', 'pais' => 'Tonga'],
    ['codigo' =>'TUR', 'pais' => 'Turqu&iacute;a'],
    ['codigo' =>'TTO', 'pais' => 'Trinidad y Tobago'],
    ['codigo' =>'TUV', 'pais' => 'Tuvalu'],
    ['codigo' =>'TWN', 'pais' => 'Taiw&aacute;n'],
    ['codigo' =>'UKR', 'pais' => 'Ucrania'],
    ['codigo' =>'UGA', 'pais' => 'Uganda'],
    ['codigo' =>'USA', 'pais' => 'Estados Unidos de Am&eacute;rica'],
    ['codigo' =>'URY', 'pais' => 'Uruguay'],
    ['codigo' =>'UZB', 'pais' => 'Uzbekist&aacute;n'],
    ['codigo' =>'VAT', 'pais' => 'Ciudad del Vaticano'],
    ['codigo' =>'VCT', 'pais' => 'San Vicente y las Granadinas'],
    ['codigo' =>'VEN', 'pais' => 'Venezuela'],
    ['codigo' =>'VGB', 'pais' => 'Islas V&iacute;rgenes Brit&aacute;nicas'],
    ['codigo' =>'VIR', 'pais' => 'Islas V&iacute;rgenes de los Estados Unidos de Am&eacute;rica'],
    ['codigo' =>'VNM', 'pais' => 'Vietnam'],
    ['codigo' =>'VUT', 'pais' => 'Vanuatu'],
    ['codigo' =>'WLF', 'pais' => 'Wallis y Futuna'],
    ['codigo' =>'WSM', 'pais' => 'Samoa'],
    ['codigo' =>'YEM', 'pais' => 'Yemen'],
    ['codigo' =>'MYT', 'pais' => 'Mayotte'],
    ['codigo' =>'ZAF', 'pais' => 'Sud&aacute;frica']
];